### ISSUE TITLE
Brightness/contrast scaling causes all visualization to disappear

### ISSUE THREAD

**Issue by oanegros** [ekatrukha/BigTrace#6]
In some images, scaling the brightness/contrast (with the tool under hotkey s) causes all visualization to disappear.

**Comment by ekatrukha** [comment]
Hi Oane,

Do you mean ROI renders or the volumetric data itself?
Are those 2-color images?

**Comment by oanegros** [comment]
Hey Eugene, 
Sorry for the sparse info in the first issue 😅
The volumetric data disappears, the ROI data remains. It's single-channel tifs, but bigTrace shows multiple channel sliders (we've seen both 2 and 3). 
We've tested a bit more and this seems to only happen in 16-bit images. In 8-bit images the hessian transform brightness does not scale under the brightness window, but the data scales fine.

**Comment by ekatrukha** [comment]
Hello Oane,

so the story with sources, that there are always # of channels + 1 sources. 
The very first source/channel is a "dummy", it is needed to keep BVV "alive". During the "crop view" operation I need to remove all "true" sources and add them back, but if there are zero sources, BVV will shut downitself. So I'm adding one empty "dummy" source at the beginning, which is there all the time. So it appears in the brightness menu.
Just ignore the first source and count from the second :)
TraceBox is always the last source. 
I hope this explanation makes sense.

There is another problem coming from BVV, that after brightness (min max) adjustment in the code it shows dataset with correct min max, but the range in sliders (shortcut S) resets itself to 0 and 65535 (or 255 for 8-bit). So then if you click and adjust it in the slider, it is updated to higher values, making dataset to "disappear". Nothing I can do about it yet.

All these problems I intend to solve in the near future by making a separate special modification of the BVV package and ship it with BigTrace, so that will be fixed. It will also allow me to add different LUTs, gamma correction, volumetric rendering, speed up the crop, etc. Probably it will happen in two months, but it is not really clear, when.

Cheers,
Eugene

**Comment by ekatrukha** [comment]
These issues should be closed in the newest release 0.1.0, check it out.

**Comment by AnaRNeves** [comment]
Hi Eugene,

I just updated BigTrace and unfortunately for the 16bit image when use try to adjust the brightness/contrast the image still disappears. Something else I noticed was that the images were squished right after loading with BigTrace, but once I press 1 to go back to the initial view they get resized to the usual shape (before the bigTrace update)

I am sending some images in attach
<img width="1434" alt="image_adjustbrightness" src="https://user-images.githubusercontent.com/82937212/193034985-49e2d6be-7ebb-4b9e-8634-b045ec80196c.png">
<img width="1434" alt="image_initial" src="https://user-images.githubusercontent.com/82937212/193035004-b8cdb061-d78e-44f1-a4df-11c79e6910dd.png">
<img width="1434" alt="image_press1" src="https://user-images.githubusercontent.com/82937212/193035011-603bdc25-06d2-47dd-9ab9-a7fa8f2f2097.png">

Cheers,
Ana

**Comment by ekatrukha** [comment]
Hello Ana,

thank you for the very detailed reply! 
Hopefully, the brightness issue is now fixed in just updated version 0.1.1
It should be on FIJI update site now, so you can just update FIJI.

Here is what the problem was:
when BigTrace loads data from tif file, it picked up brightness settings (range) that were set in ImageJ (it is stored in tif file).
Let's say in ImageJ you've put range from min 0 to max 400.
Then it renders tif file with these settings, BUT the sliders in the Brightness dialog were not updated. They would show min 0 and max 65535. 
BUT when you move the slider (probably max), it gets updated to something like 30000 (far away from needed range of 0 to 400), so that makes volume "disappear". Basically it is still there, but if a signal withing range of 0 to 400 and Brightness settings are 0 to 30000, it will be all black.
So now in the update (new version 0.1.1) after dataset is loaded, sliders take proper values.

A hint for adjustments: try to use only LUT Range slider in the beginning and fine tune it with alpha range.
The checkbox on the left synchronizes LUT sliders with alpha sliders "one way".
Also I recommend to adjust the range using >> button. If your signal is from 0 to 400 and the whole slider scale is 65535, it is hard to move slider properly.

As for squishing, can you please send me example tif with this defect to katpyxa@gmail.com? Or share it somewhere (like wetransfer)?

Thanks again for testing, I really appreciate it!

Cheers,
Eugene

**Comment by ekatrukha** [comment]
Hello Ana again,

so this squishing bug should be fixed in the latest release 0.1.2
and I am closing this issue.

Thanks again for testing and feedback!
